FROM docker.io/library/python:3.8-slim AS base

ENV PYTHONUNBUFFERED=1

WORKDIR /semantic_search_streamlit

FROM docker.io/library/python:3.8-slim AS build

WORKDIR /semantic_search_streamlit

COPY requirements.txt /semantic_search_streamlit/requirements.txt

ENV PIP_DISABLE_PIP_VERSION_CHECK=1

RUN pip install --no-cache-dir -r requirements.txt

COPY . /semantic_search_streamlit

RUN python -c "import streamlit, elasticsearch, openai, requests, dotenv"

FROM docker.io/library/python:3.8-slim AS run

ENV PYTHONUNBUFFERED=1

WORKDIR /semantic_search_streamlit

COPY requirements.txt /semantic_search_streamlit/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY . /semantic_search_streamlit

EXPOSE 8502

CMD ["python", "-m", "streamlit", "run", "app.py", "--server.port=8502", "--server.address=0.0.0.0"]

FROM docker.io/library/python:3.8-slim AS export

ENV PYTHONUNBUFFERED=1

WORKDIR /semantic_search_streamlit

COPY requirements.txt /semantic_search_streamlit/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY . /semantic_search_streamlit

EXPOSE 8502

CMD ["python", "-m", "streamlit", "run", "app.py", "--server.port=8502", "--server.address=0.0.0.0"]
